spring:
   application:
# 服务名称
      name: my-web-server-spring-boot
   datasource: # 数据源 jpa配置
      driver-class-name: com.mysql.cj.jdbc.Driver
   dbcp2: # 连接池 DBCP相关配置
      max-idle: 30
      min-idle: 10
      time-between-eviction-runs-millis: 200000
      initial-size: 10
      remove-abandoned-on-maintenance: 200000
      max-wait-millis: 30000
# 开发环境
   profiles:
      active: dev
   jpa:
      database: MYSQL # 数据库类型
      show-sql: true # 是否打印sql
      hibernate:
         naming: # 命名策略
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
         ddl-auto: update # 配置级联等级  
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
server:
   tomcat:
      uri-encoding: UTF-8
# 自定义变量 @Value("${cn.rejiejay.name}", "UTF-8")
rejiejay:
   homeTest: 曾杰杰[home]
# 腾讯云OSS对象存储 的通用配置，不管测试还是生产都是这个配置
   tencentoss:
      origin: https://rejiejay-1251940173.cos.ap-guangzhou.myqcloud.com/myserver/ # 拼接url地址的请求源
      region: ap-guangzhou # OSS 的可用地域
      bucket: rejiejay-1251940173 # COS 中用于存储数据的容器
      appid: 1251940173 # 开发者访问 COS 服务时拥有的用户维度唯一资源标识，用以标识资源
      secretid: AKIDZw6DLFgMZZKuFO6zSfdMr8D4j9KGmQeh # 开发者拥有的项目身份识别 ID，用以身份认证
      secretkey: xkIbfU4SgfT4RZVCettgEWbR2OYTBetv # 开发者拥有的项目身份密钥