server:
   port: 1938
   servlet:
      context-path: /api # 应用的上下文路径，也可以称为项目路径，是构成url地址的一部分。(测试环境独有)
spring: # 数据源和jpa配置
   datasource:
      password: QQ1938167
      url: jdbc:mysql://127.0.0.1:3306/rejiejay?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
      username: Rejiejay
rejiejay:
   file:
      upload-dir: /my-svn/myweb-server-spring-boot/uploads/