server:
   port: 3819
spring: # 数据源和jpa配置
   datasource:
      password: Qq_1938167_o0O
      url: jdbc:mysql://127.0.0.1:3306/myweb?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
      username: rejiejay
rejiejay:
   file:
      upload-dir: /root/myweb-server-spring-boot/uploads/