spring:
  application:
    # 服务名称
    name: my-web-server-spring-boot
  datasource: # 数据源 jpa配置
    driver-class-name: com.mysql.cj.jdbc.Driver
  dbcp2: # 连接池 DBCP相关配置
    max-idle: 30 
    min-idle: 10 
    time-between-eviction-runs-millis: 200000 
    initial-size: 10 
    remove-abandoned-on-maintenance: 200000 
    max-wait-millis: 30000 
  # 开发环境
  profiles: 
    active: dev
  jpa:
    database: MYSQL # 数据库类型
    show-sql: true # 是否打印sql
    hibernate:
      naming: # 命名策略
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update # 配置级联等级  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  tomcat:
    uri-encoding: UTF-8
# 自定义变量 @Value("${cn.rejiejay.name}", "UTF-8")
cn:
  rejiejay:
    homeTest: 曾杰杰[home]
